---
# ---------------------------------------------------------
# 需要常规安装到用户空间 (/data) 而非系统分区的应用关键字列表
# ---------------------------------------------------------
user_space_apps:
  - newpipe
  - solidexplorer
  # - fenix            # 不常更新，已移交 /system/app 以节省 /data 空间
  # - launcher         # 移交 /system/app，可获得系统级防杀保活特权
  # - vlc              # 不常更新，已移交 /system/app 以节省 /data 空间
  # - virtualsoftkeys  # 如果后续需要，可以随时取消注释添加到此处