---
- name: 启用 Fcitx5 输入法
  ansible.builtin.command: "{{ adb_cmd }} shell ime enable org.fcitx.fcitx5.android/.input.FcitxInputMethodService"
  ignore_errors: true

- name: 将 Fcitx5 设置为默认输入法
  ansible.builtin.command: "{{ adb_cmd }} shell ime set org.fcitx.fcitx5.android/.input.FcitxInputMethodService"


- name: 将 fcitx5 固化为系统默认输入法 (修改 defaultValue)
  ansible.builtin.shell: |
    {{ adb_cmd }} shell "sed -i \
      's|name=\"default_input_method\" value=\"[^\"]*\" package=\"android\" defaultValue=\"[^\"]*\"|name=\"default_input_method\" value=\"org.fcitx.fcitx5.android/.input.FcitxInputMethodService\" package=\"android\" defaultValue=\"org.fcitx.fcitx5.android/.input.FcitxInputMethodService\"|g' \
      /data/system/users/0/settings_secure.xml"
    {{ adb_cmd }} shell "sed -i \
      's|name=\"enabled_input_methods\" value=\"[^\"]*\" package=\"android\" defaultValue=\"[^\"]*\"|name=\"enabled_input_methods\" value=\"org.fcitx.fcitx5.android/.input.FcitxInputMethodService\" package=\"android\" defaultValue=\"org.fcitx.fcitx5.android/.input.FcitxInputMethodService\"|g' \
      /data/system/users/0/settings_secure.xml"